### ISSUE TITLE
ML training result

### ISSUE THREAD

**Issue by HOchacha** [HOchacha/Blackjack-copilot#1]

**Comment by FaltoGH** [comment]
Image source is from YouTube video: https://www.youtube.com/watch?v=fbb5nFIjMn0

![image](https://github.com/HOchacha/Blackjack-copilot/assets/70701690/d9f14337-2f5b-4b25-a261-2c169afcac5e)

First token is class (e.g. 10H is heart of ten.)
Second token is confidence of YOLOv8 object detection.
Third token is index of cluster.

As you can see, result seems good.
But more test is needed for other images, and there is a bug found in some clustering code part.
I will do more work about improving and bug fix.

The result is generated by following code. You can reference this code to get output from ML.
```python3
BEST = r"C:\Blackjack-copilot\ML\yolo\train_workspace\runs\detect\train\weights\best.pt"
TEST_IMAGE = r"C:\Blackjack-copilot\ML\yolo\train_workspace\extern_test_images\1280x720.png"

import yolo
import cluster
import cv2

model = yolo.get_model(BEST)
yresults = yolo.predict_by_image_path(model, TEST_IMAGE)
yresult = yresults[0]
cresult = cluster.predict(yresult)
final_result = cluster.get_final_result_by_yresult(yresult)
print(final_result)

im = cluster.visualize(yresult, cresult)
cv2.imshow("result", im)
cv2.waitKey()
```

Thanks.

**Comment by HOchacha** [comment]
LGTM, Can you make this code as module or Function? It would be nice if you could use it like an API in the application.

**Comment by FaltoGH** [comment]
Yes. I made a class YOLOCluster in a module in ML/yoluster.py to provide API in the application.
https://github.com/HOchacha/Blackjack-copilot/blob/a569e9208fb1f69e87181352e808826452a437f9/ML/yoluster.py#L14
Example usage python source codes are provided in ML/examples directory.

For example, predict image:
https://github.com/HOchacha/Blackjack-copilot/blob/a569e9208fb1f69e87181352e808826452a437f9/ML/examples/predict_image.py#L11-L22
Image shown:
![image](https://github.com/HOchacha/Blackjack-copilot/assets/70701690/ec2fb334-465c-49d4-a070-d4d8ad9e22e5)
Standard output:
```
WARNING ⚠️ imgsz=[720, 1280] must be multiple of max stride 32, updating to [736, 1280]
image 1/1 c:\Blackjack-copilot\ML\examples\..\yolo\train_workspace\extern_test_images\1280x720_2.png: 736x1280 2 8Ss, 1 AS, 2 JHs, 33.0ms
Speed: 4.0ms preprocess, 33.0ms inference, 1852.0ms postprocess per image at shape (1, 3, 736, 1280)
[('AS',), ('JH', '8S')]
```
Description:
`mparr` provides final result of YOLOCluster which can be used in the application.
1. If there is no playing card detected, mparr is [] (empty list).
2. If there is only one cluster detected, mparr is like [('AS', 'JH')].
3. If there are more than one clusters detected, mparr is like [('10S', '9S'), ('KH',), ('2D', 'AC')]
In third case, dealer cluster is always located in the first index (0).
The application may recommend a player's next action in only third case.

Regards,
FaltoGH

**Comment by HOchacha** [comment]
LGTM. There would be applied some parsing rule for the api result. 
Then, the part would be processed in applicational logic.
